#!/usr/bin/env python3
"""Regenerate public/study/templates.js from learning-course-templates.md.

The markdown file is the source of truth. Each `# Heading` starts a group,
each `## N. Title` starts a template, and the blockquote under it is the
prompt text. Run from anywhere:

    python3 scripts/build-study-templates.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "learning-course-templates.md"
OUT = ROOT / "public" / "study" / "templates.js"

GROUP_IDS = {
    "Learning course prompt templates": ("course", "Course design"),
    "AI tutor prompt templates": ("tutor", "Tutoring"),
}


def parse(md: str):
    templates = []
    group = None
    current = None
    quote = []

    def flush():
        nonlocal current, quote
        if current is not None:
            text = "\n".join(quote).strip()
            assert text, f"empty prompt for {current['title']}"
            current["text"] = text
            templates.append(current)
        current, quote = None, []

    for line in md.splitlines():
        m = re.match(r"^# (.+)$", line)
        if m:
            flush()
            group = GROUP_IDS[m.group(1).strip()]
            continue
        m = re.match(r"^## (\d+)\. (.+)$", line)
        if m:
            flush()
            n, title = m.groups()
            current = {
                "id": f"{group[0]}-{n}",
                "group": group[1],
                "title": title.strip(),
            }
            continue
        if current is not None:
            m = re.match(r"^> ?(.*)$", line)
            if m:
                quote.append(m.group(1))
            elif line.strip() == "" and quote:
                # blank line after the quote ends it; blank lines inside a
                # quote are written as a bare ">" so they are caught above
                flush()
    flush()
    return templates


def main():
    templates = parse(SRC.read_text(encoding="utf-8"))
    assert templates, "no templates parsed"
    body = json.dumps(templates, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// Generated by scripts/build-study-templates.py from\n"
        "// learning-course-templates.md. Do not edit by hand.\n"
        f"window.STUDY_TEMPLATES = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(templates)} templates")


if __name__ == "__main__":
    main()
