// Generates seed/catalogue.sql from seed/catalogue.json. Idempotent upsert.
import { readFileSync, writeFileSync } from "node:fs";

const { offerings } = JSON.parse(readFileSync(new URL("../seed/catalogue.json", import.meta.url), "utf8"));
const q = (v) => (v === undefined || v === null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === undefined || v === null ? "NULL" : Number(v));

const rows = offerings.map((o) => {
  const lookup = `${o.slug}_${o.interval}`;
  const cols = {
    slug: q(o.slug), kind: q(o.kind), name: q(o.name), tagline: q(o.tagline),
    description: q(o.description), price_cents: n(o.price_cents ?? 0), currency: q(o.currency ?? "aud"),
    interval: q(o.interval), stripe_lookup_key: q(o.interval === "quote" ? null : lookup),
    monthly_call_quota: n(o.monthly_call_quota), agent_slugs: q(o.agent_slugs ? JSON.stringify(o.agent_slugs) : null),
    repo_url: q(o.repo_url), sort: n(o.sort ?? 100), active: n(o.active === false ? 0 : 1),
  };
  const names = Object.keys(cols);
  const updates = names.filter((c) => c !== "slug").map((c) => `${c}=excluded.${c}`).join(", ");
  return `INSERT INTO offerings (${names.join(", ")}) VALUES (${names.map((c) => cols[c]).join(", ")})\n  ON CONFLICT(slug) DO UPDATE SET ${updates};`;
});

const out = `-- Generated by scripts/seed-sql.mjs from seed/catalogue.json. Do not edit by hand.\n${rows.join("\n")}\n`;
writeFileSync(new URL("../seed/catalogue.sql", import.meta.url), out);
console.log(`wrote seed/catalogue.sql (${offerings.length} offerings)`);
